# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: ctng build
trigger:
  branches:
    include:
      - master

jobs:
  # First job is for all non master branches, just linting, building and testing
  - job: Building
    condition: and(succeeded(), ne(variables['build.sourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - task: NodeTool@0
        displayName: Installing Node.js
        inputs:
          versionSpec: '12.14.1'

      - task: Npm@1
        displayName: Installing npm dependencies
        inputs:
          command: install
          customEndpoint: Matthias NPMJS

      - script: npm run lint:libs
        displayName: Linting libraries

      - script: npm run build:libs:release
        displayName: Building libraries

      - script: npm run test:libs
        displayName: Testing libraries

    # Second job only runs on master and if it is not requested for our build service (this is the case after updating the versions in CI)
  - job: Releasing
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'), ne(variables['build.requestedFor'], 'Project Collection Build Service (codetrust)'))
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - checkout: self
        persistCredentials: true

      - script: git checkout master && git config user.email "pipeline@azure-devops.com" && git config user.name "DevOps Pipeline"
        displayName: Checking out master branch

      - task: NodeTool@0
        enabled: true
        displayName: Installing Node.js
        inputs:
          versionSpec: '12.14.1'

      - task: Npm@1
        enabled: true
        displayName: Installing npm dependencies
        inputs:
          command: install
          customEndpoint: Matthias NPMJS

      - script: npm run semver
        displayName: Versioning libraries

      - script: npm run build:libs:release
        displayName: Building libraries

      - task: Npm@1
        enabled: true
        displayName: Publishing npm packages
        inputs:
          command: custom
          customCommand: run deploy
          customEndpoint: Matthias NPMJS
